# APISIX Configuration

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0  # Allow admin API access from any IP address - restrict this in production
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1  # Default key, change in production
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

etcd:
  host:
    - "http://etcd:2379"  # etcd service name in docker-compose
  prefix: "/apisix"
  timeout: 30

apisix:
  node_listen:
    - 9080
    - 9443
  enable_ipv6: false
  enable_control: true
  enable_reuseport: true
  enable_dev_mode: false  # Set to true only for development
  enable_admin_cors: true

plugins:                          # Plugin list
  - prometheus
  - key-auth
  - basic-auth
  - jwt-auth
  - cors
  - rate-limit
  - proxy-rewrite
  - response-rewrite
  - grpc-transcode
  - serverless-pre-function
  - serverless-post-function
  - ip-restriction
  - limit-req
  - limit-count
  - limit-conn
  - fault-injection
  - request-validation
  - proxy-cache
  - server-info
  - traffic-split

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

# nginx configuration parameters
nginx_config:
  worker_processes: auto
  worker_rlimit_nofile: 20480
